version: '3.8'

services:
  web:
    build: .
    container_name: pg-web
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: pg-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pg_rental
    ports:
      - "3306:3306"
